# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 竭尽全力
name: Tristan Cao
email: caocmh@qq.com
location: Xi'an, China
company: Inventec Besta Co., Ltd.
company_url: http://www.inventec.com/
github_url: https://github.com/caocmh
description: This is a personal website of Tristan Cao | 个人博客，用于记录学习笔记
favicon: favicon.png # Image must be in assets/images
url: http://caocmh.github.io # the base hostname & protocol for your site

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"

source: .
destination: ./_site

quiet: false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: z-beatles.disqus.com

# Pagination
paginate: 8
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
# analytics :
#   provider : google
#   google :
#       tracking_id : 'UA-72165600-1'


# For about.html. Fell free to create your own!

skill_Tools_keywords: [visual studio 2013, Android studio2.2]
skill_program_keywords: [C, C++, JAVA, python]
skill_Android_keywords: [Android]
skill_Computer_Network_keywords: [IP, TCP, UDP, HTTP]
skill_SQL_keywords: [My SQL, SQL server, Oracle SQL, Sqlite]
skill_OS_keywords: [Windows, Linux, Mac os]
